# Config version: Do not touch this.
version: 1.0

# Language file. Will look for a file called <ARG>.yml in the lang folder.
# If the file does not exist, it will be automatically created for you to edit.
# Example: 'en' will look for /lang/en.yml
language: en

# Warmup time (in s). Determines the time a player needs to stand still before he gets teleported.
# Teleport will be aborted if he moves or gets harmed during warmup phase.
warmup-time: 0

# Cooldown time (in s). Determines the time a player cannot issue another teleport within x seconds after the last one.
cooldown-time: 0

# Maximum amount of homes.
max-homes: 1

# Storage method. Define where the home data should be stored:
# - File (yml-files in the 'data' folder)
# - MySQL
storage-method: File

# MySQL configuration. Skip this if you do not use MySQL as storage method.
mysql:
  host: 127.0.0.1
  port: 3306
  database: database
  user: user
  password: password

# Enable debug messages.
debug: false